### ISSUE TITLE
Scrolling-issue in Wordstar with 80x24 Window in Windows

### ISSUE THREAD

**Issue by guidol70** [davidly/ntvcm#4] opened 2024-01-29 12:14 UTC
Dear David,
firstly: Many thanks for creating the cool VMs ntvcm and ntvdm :)
They do work very well under armbian (debian/Linux) and Windows (used mingw32 & mingw64)
and doesnt hog the cpu like some other emulators!

The included Wordstar does scroll fine in a puTTY-session (also without the -c commandline-option) whatever windows-size I use.

But when I compile ntvcm on Windows with mingw32 or mingw64 I had to use the -c commandline option (no problem) because without it the input-field for the filename to load isnt at the same line as the prompt-text for the filename.

And the screen-window for ntvcm (I use on Windows Cmder/ConEmu because it includes VT100/ANSI-Emulation) has to be 80x25 (like in DOS or ntvdm) also when using the -c commandline option, because when using a 80x24 (for CP/M screen size) screen-windows the ouput gets distorted when scrolling down (Ctrl-X) and up (Ctrl-E)

I think I/we have to use 80x24 for CP/M because of the documentation/help of the commandline-switches from ntvcm.

Kind regards
Guido

**Comment by davidly** [comment] 2024-01-29 15:44
Hi Guido!

Thank you for reporting this bug!

Is the requested change to allow ntvcm to work with both 80x25 and 80x24? CP/M apps like Wordstar assume 24. They'll work with more lines, when scrolling up and down but at some point the lines beyond 24 will become stale because they're not refreshed. 

The calls to EstablishConsoleOutput() in ntvcm.cxx can be changed from 24 to 25 and Wordstar will use the bottom line when scrolling, but then the last line won't be updated after pageup /pagedown. 

I've only tested using CMD.EXE in Windows, which has VT100 emulation built in. Does Cmder/ConEmu work better?

I'm not sure if I answered your question -- did I misunderstand it?

Thanks,
David

**Comment by guidol70** [comment] 2024-01-30 09:51
Hi David,
no I dont want to request that ntvcm will work with 25 lines ;)
I want (please) to request that it will work with 24 lines in windows.

OK - I tested it also with CMD, but there it does only work in non-legacy.mode (see 1st settings tab of CMD) - because only in non-legacy-mode it supports VT100/ANSI.

In legacy mode you need to use ansicon to insert VT100/ANSI-support.
Cmder/ConEmu has VT100/ANSI support, but the screen in Wordstar gets distorted when scrolling while the window is set to 80x24 (which isnt the case on a Linux-compile)
In 80x25 the scrolling is OK (but as you know the line 25 isnt updated right).

I like the possibility of Cmder to set the the normal and bold color like in puTTY:

![ntvcmg32_Wordstar_Cmder](https://github.com/davidly/ntvcm/assets/5121124/7c9d89b1-6041-47eb-bc93-3036227c5fde)

BTW: I also did try to use ntvcm under debian 12 on a Powerbook G4 with PowerPC-CPU (ppc).
It does compile but wont start the app - is just quits after recognizing the App (-Size)  :(

[ntvcm_deb12_ppc.log](https://github.com/davidly/ntvcm/files/14095755/ntvcm_deb12_ppc.log)

ntvdm on the ppc-debian-12 says its cant load the executeable:

```
/home/guido/ntvdm-main/wordstar# ../ntvdm -t ./WS.EXE
unable to load executable
  Built for (other) debug on 29 Jan 24 20:47:49 by g++ on linux

```

[ntvdm_deb12_ppc.log](https://github.com/davidly/ntvcm/files/14095836/ntvdm_deb12_ppc.log)

BUT both (ntvcm & ntvdm on debian 12 ppc) does show the help-screen 
if I didnt add any option/switches to the commandline

**Comment by guidol70** [comment] 2024-01-30 12:44
as additionally info ;)
You could also use puTTY/kiTTY as VT100/ANSI-terminal for Windows (10) if you install the local OpenSSH-Server like 
https://lehwalder.wordpress.com/2022/10/22/running-runcpm-win-in-putty-with-win10/

With puTTY/kiTTY Wordstar for CP/M also works better in 80x24 - while scrolling - with ntvcmg(32)
(**BUT** I cant find the color-setting to change this bold-yellow to orange like the cursor :( )

![ntvcm_via_putty_local_and_OpenSSH](https://github.com/davidly/ntvcm/assets/5121124/7173b120-c0b5-4d84-8a10-9c05a316c754)

**Comment by davidly** [comment] 2024-01-30 15:31
Thanks for the clarifications -- I'm going to install those tools and reproduce the behavior so I can fix it.

As for PowerPC on the Mac -- I'm almost certain it's because that machine is big-endian.  My code makes many little-endian assumptions. I think they could be fixed pretty easily, but I don't have a big-endian machine to test with. Hmm, there's probably an emulator I can find.

David

**Comment by guidol70** [comment] 2024-01-30 16:54
> As for PowerPC on the Mac -- I'm almost certain it's because that machine is big-endian. My code makes many little-endian assumptions. I think they could be fixed pretty easily, but I don't have a big-endian machine to test with. Hmm, there's probably an emulator I can find.

OK - thats seems to be true for the Powerbook :(

```
root@powerbook(192.168.6.244):/home/guido/ntvcm-main# 
uname -a
Linux powerbook 6.6.13-powerpc #1 Debian 6.6.13-1 (2024-01-20) ppc GNU/Linux

lscpu | grep -i endian
Byte Order:          Big Endian

```

compiling with "-mbig-endian" alone doenst seem to help... but thanks for looking into it ;)

Kind regards
Guido

**Comment by guidol70** [comment] 2024-01-30 17:29
a Console2 Screenshot:

![Console2_ANSI_Terminal](https://github.com/davidly/ntvcm/assets/5121124/af4369b9-3a70-4fd6-949d-19bc659a1100)

**Comment by davidly** [comment] 2024-01-31 18:35
OK, I have a repro in Cmder/ConEmu. 

My best guess right now is that it's a bug in Cmder/ConEmu. Ntvcm is just passing on escape sequences from the app with no translation and Cmder/ConEmu apparently has off-by-one bugs when in 80x24 mode. 

I wrote a very simple app that demonstrates the bug. It should be built alongside ntvcm as it shares include file dependencies. When run in Cmder/ConEmu in 80,25 mode it works well and identically to CMD.EXE. When run in 80x24 mode it fails in a manner similar to how ntvcm running WordStar and other apps fail. I'm not sure how to report the bug to the Cmder/ConEmu owners or if it's worth their time to fix it :)

```
#include <stdio.h>
#include <assert.h>

#include <djl_os.hxx>
#include <djltrace.hxx>
#include <djl_con.hxx>

CDJLTrace tracer;
ConsoleConfiguration g_consoleConfig;

int main( int argc, char * argv[] )
{
    g_consoleConfig.EstablishConsoleOutput( 80, 24 );

    printf( "\x1b%c", 'c' ); // reset terminal
    printf( "\x1b%c",'m' ); // reset formatting
    printf( "\x1b[H" ); // home cursor

    for ( int i = 0; i < 24; i++ )
    {
        printf( "\x1b[%d;1H", i + 1 );
        printf( "line %d", i );
    }

    printf( "\x1b[1;1H" ); // home cursor
    printf( "brand new line 0" );

    g_consoleConfig.portable_getch();
    g_consoleConfig.RestoreConsole( false );
}
```

CMD.EXE and Cmder/ConEmu in 80,25 mode shows this:

        brand new line 0
        line 1
        line 2
        line 3
        line 4
        line 5
        line 6
        line 7
        line 8

Cmder/ConEmu in 80,24 mode shows this:

        ine 0             
        brand new line 0  
        line 2            
        line 3            
        line 4            
        line 5            
        line 6            
        line 7            
        line 8

**Comment by davidly** [comment] 2024-01-31 18:44
I'm going to close this issue now given that I believe it's not a bug in ntvcm.

Please feel free to re-open if new information becomes available :)

**Closed by davidly** 2024-01-31 18:44 UTC
